// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('e:/AwesomeProject/node_modules/react');
var { Component } = React;
var ReactNative = require('e:/AwesomeProject/node_modules/react-native');
var { AppRegistry } = ReactNative;
var entryPoint = require('e:/AwesomeProject/index.js');
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('AwesomeProject', appParameters);
});